- type: job
  id: Anomaly
  name: job-name-anomaly
  description: job-description-anomaly
  playTimeTracker: JobAnomaly
  startingGear: AnomalyGear
  alwaysUseSpawner: true
  overrideConsoleVisibility: true
  canBeAntag: false
  canBeAntagTarget: false
  icon: "JobIconNoId"
  joinNotifyCrew: false
  whitelisted: false
  access:
  - Maintenance
  requirements:
    - !type:CharacterSpeciesRequirement
      species:
        - Shadowkin
    - !type:CharacterOverallTimeRequirement
      min: 360 #6 hrs claw command
  special:
  - !type:AddComponentSpecial
    components:
      - type: AnomalyJob
      - type: Clumsy
        ClumsyDefaultCheck: 1
        gunShootFailDamage:
          types:
            Blunt: 5
            Piercing: 4
          groups:
            Burn: 3

- type: startingGear
  id: AnomalyGear
  equipment:
    jumpsuit: ClothingUniformNudityPermit
    shoes: ClothingClothWrap
    id: AnomalyIDCard
    ears: ClothingHeadsetGrey
